### ISSUE TITLE
rtmdnet no LTDSE.yaml and complie.sh

### ISSUE THREAD

**Issue by kuiran** [Daikenan/LTMU#25]
![image](https://user-images.githubusercontent.com/25083462/101275832-c066d280-37e3-11eb-9ff6-276c1ef27d61.png)

**Comment by Daikenan** [comment]
These bugs have been fixed.

**Comment by kuiran** [comment]
![image](https://user-images.githubusercontent.com/25083462/101332550-67b13b80-38b0-11eb-9438-db837fe8783f.png)
thanks your response, but  demo.py still can't run,and i can't find the sample_generator even global search.How to fix it.

**Comment by Daikenan** [comment]
Oh, that was a small bug, now it has been fixed, you can update the code.
